name: Postman API tests running with Newman cli

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  newman-tests:
    name: Run Postman Tests with Newman
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman tests using Newman
        run: newman run tests/reqres.postman_collection.json

      - name: Run Postman tests using Newman via shell script
        run: |
          chmod +x run-api-tests.sh
          ./run-api-tests.sh
